project: Tempura

cocoapods:
  public_repo:
    email: opensource@bendingspoons.com
    author: Bending Spoons
  skip_linting: true

  tests:
  runs:
    - scheme: Tempura
      sdk: iphonesimulator11.3
      simulator: platform=iOS Simulator,OS=11.3,name=iPhone 7