project: Tempura

cocoapods:
  public_repo:
    email: opensource@bendingspoons.com
    author: Bending Spoons
  skip_linting: true

  tests:
  runs:
    - scheme: Tempura
      sdk: iphonesimulator12.0
      simulator: platform=iOS Simulator,OS=12.0,name=iPhone 8