language: swift
osx_image: xcode10
env:
  global:
    - PROJECT=Tempura.xcworkspace
  matrix:
    - SCHEME="Tempura"
      SDK=iphonesimulator12.0
      SIMULATOR="platform=iOS Simulator,OS=12.0,name=iPhone 8"

before_install:
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 8 (12.0" | awk -F '[ ]' '{print $4}' | awk -F '[[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
  - pod repo update > /dev/null

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices

  # Build Framework in Debug and Run Tests if specified
  - travis_retry xcodebuild -workspace $PROJECT -scheme "$SCHEME" -sdk $SDK test -destination "$SIMULATOR" | xcpretty -c
